InventoryWeb/Controllers/InventoryController.cs
using InventoryWeb.Core.Models.Domains;
using InventoryWeb.Core.Repositories;
using InventoryWeb.Core.Service;
using InventoryWeb.Core.ViewModels;
using InventoryWeb.Persistence;
using InventoryWeb.Persistence.Extensions;
using InventoryWeb.Persistence.Repositories;
using InventoryWeb.Persistence.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryWeb.Controllers
{
    public class InventoryController : Controller
    {
        private IUnitService _unitService;
        private IInventoryService _inventoryService;
        private IProductBaseService _productBaseService;
        public InventoryController(IUnitService unitService, IInventoryService inventoryService, IProductBaseService productBaseService)
        {
            _unitService = unitService;
            _inventoryService = inventoryService;
            _productBaseService = productBaseService;
        }
        public IActionResult Inventory()
        {
            
            var userId = User.GetUserId();

            var vm = new InventoriesViewModel
            {
                Inventory = _inventoryService.GetInventory(userId, 0),
                Inventories = _inventoryService.Get(userId),
                Product = new Product()
            };
            return View(vm);
        }
        public IActionResult InventoryPreview(int id)
        {
            var inv = _inventoryService.GetPreview(id);
            var products = _inventoryService.GetAllProducts(id);

            var vm = new InventoryViewModel
            {
                Inventory = inv,
                Products = _inventoryService.GetProduct(inv.Id),
                Units = _unitService.GetUnit(),
                Product = new Product()
            };
            vm.Inventory.Value = _inventoryService.GetValueAll(id);

            return View("InventoryPreview", vm);
        }

        public IActionResult GetInventoryProducts(int inventoryId)
        {
            var products = _inventoryService.GetProduct(inventoryId);
            var viewModel = new InventoryViewModel
            {
                Products = products
            };
            return RedirectToAction("InventoryPreview", viewModel);
        }
        public IActionResult FindProducts(string kodinput)
        {
            var product = _productBaseService.GetProductBase(kodinput);
            if (product != null)
            {
                var productName = product.NameProductDb;
                var productPrice = product.EachPrice;
                return Json(new { success = true, productName, productPrice });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        public IActionResult AddInventory(Inventory inventory)
        {
            ModelState.Remove("Inventory.Id");
            if (ModelState.IsValid)
            {
                inventory = new Inventory
                {
                    Name = inventory.Name,
                    Company = inventory.Company,
                    Date = DateTime.Now,
                    UserId = User.GetUserId(),
                };
                _inventoryService.AddInventory(inventory);

                return RedirectToAction("Inventory");
            }
            else
                return View(inventory);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProduct(InventoryViewModel model)
        {
            var product = new Product
            {
                ProductName = model.Product.ProductName,
                Code = model.Product.Code,
                InventoryId = model.Inventory.Id,
                Price = model.Product.Price,
                Quantity = model.Product.Quantity,
                UnitId = model.Product.UnitId,
                ProductValue = model.Product.Price * model.Product.Quantity,
            };

            if (!ModelState.IsValid)
            {
                return View(product);
            }
            _inventoryService.AddProduct(product);

            return RedirectToAction("ProductTablePartial", new { id = model.Inventory.Id });
        }
        public IActionResult ProductTablePartial(int id)
        {
            var products = new InventoryViewModel
            {
                Inventory = new Inventory { Id = id },
                Products = _inventoryService.GetAllProducts(id)
            };
            products.Inventory.Products = _inventoryService.GetAllProducts(id);
            return PartialView("_ProductsTable", products);
        }
        [HttpGet]
        public IActionResult CalculateInventoryValue(int inventoryId)
        {
            var inventoryValue = _inventoryService.GetValueAll(inventoryId);

            return Json(new { inventoryValue });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                var userId = User.GetUserId();
                _inventoryService.Delete(id, userId);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }

            return Json(new { success = true });
        }
        [HttpPost]
        public IActionResult DeleteProduct(int id)
        {
            try
            {
                _inventoryService.DeleteProduct(id);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }

            return Json(new { success = true });
        }

        [HttpPost]
        public IActionResult EditProduct(Product prodToUpdate)
        {
            var updatedProduct = _inventoryService.GetProductById(prodToUpdate.Id);

            updatedProduct.Code = prodToUpdate.Code;
            updatedProduct.ProductName = prodToUpdate.ProductName;
            updatedProduct.Price = prodToUpdate.Price;
            updatedProduct.UnitId = prodToUpdate.UnitId;
            updatedProduct.Quantity = prodToUpdate.Quantity;
            updatedProduct.ProductValue = prodToUpdate.Price * prodToUpdate.Quantity;
            if (ModelState.IsValid)
            {
                _inventoryService.Update(updatedProduct);

                return Json(new { success = true });
            }

            return Json(new { success = false, updatedProduct });
        }
    }
}

InventoryWeb/Controllers/PrintController.cs
using InventoryWeb.Persistence;
using InventoryWeb.Persistence.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using InventoryWeb.Persistence.Extensions;
using System.Drawing;
using InventoryWeb.Core.Models.Domains;

using InventoryWeb.Core.ViewModels;
using DinkToPdf.Contracts;
using DinkToPdf;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Routing;

namespace InventoryWeb.Controllers
{
    public class PrintController : Controller
    {
        private InventoryRepository _inventoryRepository;
        private IConverter _converter;
        private IRazorViewEngine _viewEngine;
        private ITempDataProvider _tempDataProvider;
        private IServiceProvider _serviceProvider;

        public PrintController(ApplicationDbContext context, IConverter converter, IRazorViewEngine viewEngine,
                         ITempDataProvider tempDataProvider, IServiceProvider serviceProvider)
        {
            _inventoryRepository = new InventoryRepository(context);
            _converter = converter;
            _viewEngine = viewEngine;
            _tempDataProvider = tempDataProvider;
            _serviceProvider = serviceProvider;
        }
        public async Task<IActionResult> InventoryToPdf(Inventory inventory)
        {
            var inventoryViewModel = new InventoryViewModel
            {
                Inventory = inventory,
                Products = _inventoryRepository.GetProduct(inventory.Id)
            };

            var htmlContent = await RenderViewToStringAsync("Print/InventoryPrintTemplate", inventoryViewModel);

            var doc = new HtmlToPdfDocument()
            {
                GlobalSettings = {
                PaperSize = PaperKind.A4,
                Orientation = Orientation.Portrait,
            },
                Objects = {
                    new ObjectSettings()
                    {
                        HtmlContent = htmlContent,
                    }
                }
            };

            var pdfBytes = _converter.Convert(doc);
            return File(pdfBytes, "application/pdf", $"Inventaryzacja_{inventory.Id}.pdf");
        }
        private async Task<string> RenderViewToStringAsync(string viewName, object model)
        {
            var httpContext = new DefaultHttpContext { RequestServices = _serviceProvider };
            var actionContext = new ActionContext(httpContext, new RouteData(), new ControllerActionDescriptor());

            using (var sw = new StringWriter())
            {
                var viewResult = _viewEngine.FindView(actionContext, viewName, false);
                if (viewResult.View == null)
                {
                    throw new ArgumentNullException($"{viewName} does not match any available view");
                }

                var viewDictionary = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary())
                {
                    Model = model
                };

                var viewContext = new ViewContext(
                    actionContext,
                    viewResult.View,
                    viewDictionary,
                    new TempDataDictionary(actionContext.HttpContext, _tempDataProvider),
                    sw,
                    new HtmlHelperOptions()
                );

                await viewResult.View.RenderAsync(viewContext);
                return sw.ToString();
            }
        }

        public ActionResult DownloadInventoryPdf(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] == null)
                throw new Exception("Błąd przy próbie eksportu faktury do PDF.");

            var data = TempData[fileGuid] as byte[];
            return File(data, "application/pdf", fileName);
        }

        public ActionResult PrintInventory(int id)
        {
            var userId = User.GetUserId();
            var inventory = new InventoryViewModel
            {
                Inventory = _inventoryRepository.GetInventory(userId, id),
                Products = _inventoryRepository.GetProduct(id),
            };
            inventory.Inventory.Value = GetValueAll(inventory);
            return View("InventoryPrintTemplate", inventory);
        }
        private decimal GetValueAll(InventoryViewModel products)
        {
            decimal val = 0;
            foreach (var item in products.Products)
            {
                val += item.ProductValue;
            };
            return val;
        }
    }
}

InventoryWeb/Controllers/UnitController.cs
using InventoryWeb.Persistence.Repositories;
using InventoryWeb.Persistence;
using Microsoft.AspNetCore.Mvc;
using InventoryWeb.Persistence.Extensions;
using InventoryWeb.Core.Models.Domains;
using InventoryWeb.Core.ViewModels;
using System;
using Microsoft.EntityFrameworkCore;
using InventoryWeb.Persistence.Services;
using InventoryWeb.Core.Service;
using InventoryWeb.Core.Repositories;
using Newtonsoft.Json;

namespace InventoryWeb.Controllers
{
    public class UnitController : Controller
    {
        private IUnitService _unitService;
        public UnitController(IUnitService unitService)
        {
            _unitService = unitService;
        }
        public IActionResult Units()
        {
            var units = _unitService.GetUnits();
            var vm = new UnitViewModel();
            vm.Units = units;

            return View(units);
        }
        public IActionResult Unit()
        {
            var vm = new UnitViewModel
            {
                Units = _unitService.GetUnits()
            };
            return View(vm);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                var userId = User.GetUserId();
                _unitService.Delete(id);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }

            return Json(new { success = true });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUnit(Unit unit)
        {
            unit = new Unit
            {
                UnitName = unit.UnitName,
            };
            ModelState.Remove("unit.Id");

            if (!ModelState.IsValid)
            {
                return View(unit);
            }
            _unitService.Add(unit);
            return RedirectToAction("UnitsTablePartial");
        }
        public IActionResult UnitsTablePartial()
        {
            var units = new UnitViewModel
            {
                Units = _unitService.GetUnits(),
            };
            return PartialView("_UnitsTable", units);
        }
    }
}

InventoryWeb/Views/Inventory/InventoryPreview.cshtml
@model InventoryViewModel

@Html.AntiForgeryToken()

<!--Add Product-->
<div class="modal fade" id="AddProdModal" tabindex="-1" role="dialog" aria-labelledby="AddProdModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="saveFormProdBase" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Inventory.Id">
                <input type="hidden" asp-for="Inventory.Company">
                <input type="hidden" asp-for="Inventory.Name">
                <input type="hidden" asp-for="Product.InventoryId">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Nowy Produkt</h5>
                </div>
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <label id="scanLabel" asp-for="Product.Code" class="control-label">Zeskanuj kod lub wpisz ręcznie</label>
                    </div>
                    <div class="form-group">
                        <label asp-for="Product.Code" class="control-label" style="font-weight:bolder">Kod:</label>
                        <input asp-for="Product.Code" class="form-control" id="kodinput" />
                        <span asp-validation-for="Product.Code" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Product.ProductName" class="control-label" style="font-weight:bolder">Nazwa produktu:</label>

                        <div class="input-group">
                            <input asp-for="Product.ProductName" class="form-control" id="nameinput" />
                            <div class="input-group-append" data-toggle="tooltip" data-placement="right" title="Dodaj do bazy produktów. Pole kod, nazwa produktu i cena będą zapisane.">
                                <button class="btn btn-dark" id="addprodDb" type="button">
                                    <i class="bi bi-plus-lg"></i>
                                </button>
                            </div>
                        </div>
                        <span asp-validation-for="Product.ProductName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Product.UnitId" class="control-label" style="font-weight:bolder">Jednostka:</label>
                        @Html.DropDownListFor(x => x.Product.UnitId,
                        new SelectList(Model.Units, "Id", "UnitName"),
                        "-- wybierz jednostkę --", new { @class = "form-control ", id="unitinput"} )
                        @Html.ValidationMessageFor(x => x.Product.UnitId)
                    </div>
                    <div class="form-group">
                        <label asp-for="Product.Quantity" class="control-label" style="font-weight:bolder">Ilość:</label>
                        <input asp-for="Product.Quantity" class="form-control" id="quantityinput" />
                        <span asp-validation-for="Product.Quantity" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Product.Price" class="control-label" style="font-weight:bolder">Cena:</label>
                        <input asp-for="Product.Price" class="form-control" id="priceinput" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-Cancel" data-dismiss="modal">Zakończ</button>
                    <button type="button" id="btnSaveProd" class="btn btn-primary">Dodaj</button>
                </div>
            </form>
        </div>
    </div>
</div>
@await Html.PartialAsync("_ProductsTable", Model)

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@section Scripts{

    <script>

        $('#AddProdModal').on('shown.bs.modal', function () {
            $('#priceinput').val('');
            $('#quantityinput').val('');
            $('#kodinput').focus();
        });

        var timerid;
        $('#kodinput').on('input', function (e) {

            clearTimeout(timerid);

            var button = document.getElementById("addprodDb");
            button.innerHTML = '<i class="bi bi-plus-lg"></i>';
            var code = e.target.value;
            if (code === "") {
                $('#scanLabel').show();
            } else {
                $('#scanLabel').hide();
            }

            timerid = setTimeout(function () {
                var code = e.target.value;
                $.ajax({
                    type: "Get",
                    url: '@Url.Action("FindProducts")',
                    data: { kodinput: code },
                    success: function (data) {
                        if (data.productName) {
                            var priceVal = data.productPrice.toString().replace(".", ",");
                            $('#nameinput').val(data.productName);
                            $('#priceinput').val(priceVal)
                            $('#unitinput').focus();                         
                            button.innerHTML = '<i class="bi bi-check-lg"></i>';
                        }
                        else {
                            $('#nameinput').val("");
                            $('#priceinput').val('');
                        }
                    }

                })
            }, 550);
        });

        $("#btnSaveProd").click(function () {
            var prodForm = $("#saveFormProdBase").serialize();
            var button = document.getElementById("addprodDb");

            $.ajax({
                type: "POST",
                url: '@Url.Action("AddProduct", "Inventory")',
                data: prodForm,
                success: function (data) {
                    calculateAndUpdateInventoryValue();
                    $('#nameinput').val('');
                    $('#kodinput').val('');
                    $('#unitinput').val('');
                    $('#quantityinput').val('');
                    $('#priceinput').val('');
                    $('#kodinput').focus();
                    button.innerHTML = '<i class="bi bi-plus-lg"></i>';
                    $("#productTable").html(data);
                },
                        error: function (data) {
                    alert("Ne udało sie dodać produktu.\nSprawdź czy wszystkie pola sa wypełnione.");
                }
            })
        })

        function deleteProduct(id, btn) {
            if (!confirm("Czy na pewno chcesz usunąć produkt?"))
                return;

            $.ajax({
                type: "POST",
                url: "@Url.Action("DeleteProduct", "Inventory")",
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.success) {
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                        calculateAndUpdateInventoryValue();

                    } else {
                        alert(data.message);
                    }
                },
                error: function (data) {
                    alert(data.message)
                },
                dataType: "json"
            });
        }

        function editProduct(productId) {
            var invProd = $("#editForm-" + productId).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("EditProduct", "Inventory")',
                data: invProd,
                success: function (data) {
                    if (data.success) {
                        $(".modal-backdrop").remove();
                        $("#EditProdModal-" + productId).modal("hide").on("hidden.bs.modal", function () {
                        });
                        location.reload();
                    } else {
                        alert("Błąd podczas edycji produktu.\nSprawdź czy wszystkie polą sa wypełnione");
                    }
                }
            });
        }
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $('[data-toggle="tooltip"]').on('click', function () {
                $(this).tooltip('hide');
            });
        });


        document.getElementById("addprodDb").addEventListener("click", function () {
            var productDb = $("#saveFormProdBase").serialize();
            var button = this;

            $.ajax({
                type: "POST",
                url: '@Url.Action("AddProductDbs", "ProductsBase")',
                data: productDb,
                success: function (data) {
                    if (data.success) {
                        button.innerHTML = '<i class="bi bi-check-lg"></i>';
                    }
                    else {
                        alert("Pole kod i nazwa produktu są wymagane!")
                    }
                },
            });
        });

        function generatePdf() {

            $.ajax({
                type: 'POST',
                url: "@Url.Action("InventoryToPdf", "Print")",
                data: {
                    id: '@Model.Inventory.Id'
                },
                success: function (data) {
                    window.location = '@Url.Action("DownloadInventoryPdf", "Print")' + '?fileGuid=' + data.FileGuid + '&fileName=' + data.FileName;
                },
                error: function (data) {
                    alert(data.Message);
                },
                dataType: 'json',
                cache: false
            });
        }

        function printInvoice() {
            var url = '@Url.Action("PrintInventory", "Print")' + '?id=' + '@Model.Inventory.Id';

            var myWindow = window.open(url, '');

            myWindow.onload = function () {
                myWindow.print();
                myWindow.onafterprint = function () {
                    myWindow.close();
                };
            };
        }
        function calculateAndUpdateInventoryValue() {
            var inventoryId = $("#Inventory_Id").val();
            $.ajax({
                type: "GET",
                url: '@Url.Action("CalculateInventoryValue", "Inventory")' + '?inventoryId=' + inventoryId,
                success: function (data) {
                    var formattedInventoryValue = data.inventoryValue.toString().replace(".", ",");
                    $("#inventoryValue").text("Całkowita wartość: " + formattedInventoryValue + " zł");
                }
            });
        }

        var colors = ["black", "red"];
        var currentColorIndex = 0;

        function toggleScanLabel() {
            var scanLabel = document.getElementById("scanLabel");
            scanLabel.style.color = colors[currentColorIndex];

            currentColorIndex = (currentColorIndex + 1) % colors.length;
        }

        setInterval(toggleScanLabel, 750);
    </script>
}

InventoryWeb/Views/Inventory/_EditProduct.cshtml
@model InventoryWeb.Core.Models.Domains.Product

<div class="modal fade text-lg-start" id="EditProdModal-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="EditProdModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="editForm-@Model.Id">
                <input type="hidden" name="Id" value="@Model.Id" />
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edytuj Produkt</h5>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Code" class="control-label" style="font-weight:bolder">Kod:*</label>
                        <input asp-for="Code" class="form-control" autofocus />
                        <span asp-validation-for="Code" class="text-danger"></span>

                        <label asp-for="ProductName" class="control-label" style="font-weight:bolder">Nazwa produktu:*</label>
                        <input asp-for="ProductName" class="form-control" />
                        <span asp-validation-for="ProductName" class="text-danger"></span>

                        <label asp-for="UnitId" class="control-label" style="font-weight:bolder">Jednostka:*</label>
                        <input asp-for="UnitId" class="form-control"/>
                        <span asp-validation-for="UnitId" class="text-danger"></span>

                        <label asp-for="Quantity" class="control-label" style="font-weight:bolder">Ilość:*</label>
                        <input asp-for="Quantity" class="form-control" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>

                        <label asp-for="Price" class="control-label" style="font-weight:bolder">Cena:*</label>
                        <input asp-for="Price" class="form-control" />
                    </div>
                    <label style="color:red">
                        * - pola wymagane
                    </label>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-Cancel" data-dismiss="modal">Anuluj</button>
                    <button type="button" class="btn btn-primary" onclick="editProduct('@Model.Id')">Zapisz</button>
                </div>
            </form>
        </div>
    </div>
</div>

InventoryWeb/Views/Inventory/_InventoryTable.cshtml
@model IEnumerable<InventoryWeb.Core.Models.Domains.Inventory>


<div id="InventoryTable">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#AddModal" data-whatever="">Nowa Inwentaryzacja </button>
    <a type="button" class="btn btn-secondary" asp-controller="Unit" asp-action="Unit">Jednostki</a>
    <a type="button" class="btn btn-secondary" asp-controller="ProductsBase" asp-action="ProductsDb">Baza Produktów</a>
    <table class="table mt-3  text-center">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nazwa inwentarza</th>
                <th scope="col">Firma</th>
                <th scope="col">Data utworzenia</th>
                <th scope="col">Akcje</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var inventory in Model)
                {
                    <tr>
                        <td>
                            <a class="title-container text-center w-100 h-100" data-inventory-id="@inventory.Id" onclick="window.location.href = '@Url.Action("InventoryPreview", "Inventory", inventory)'" style="cursor: pointer;">
                                <div class="title-overlay font-weight-bold">
                                    @inventory.Name
                                </div>
                            </a>
                        </td>
                        <td>
                            @inventory.Company
                        </td>
                        <td>
                            @inventory.Date
                        </td>
                        <td>
                            <button class="btn btn-danger btn-sm"
                                    onclick="deleteInventory('@inventory.Id', this)">
                                Usuń
                            </button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-center" colspan="6">
                        Brak inwentaryzacji do wyświetlenia!
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>